//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `cmdvel.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __jderobot_cmdvel_h__
#define __jderobot_cmdvel_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace jderobot
{

class CMDVelData;
class CMDVel;
class CMDVelPrx;

}

namespace jderobot
{

class CMDVel : public virtual ::Ice::Object
{
public:

    using ProxyType = CMDVelPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual int setCMDVelData(::std::shared_ptr<CMDVelData> data, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_setCMDVelData(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace jderobot
{

class CMDVelData : public ::Ice::ValueHelper<CMDVelData, ::Ice::Value>
{
public:

    virtual ~CMDVelData();

    CMDVelData() = default;

    CMDVelData(const CMDVelData&) = default;
    CMDVelData(CMDVelData&&) = default;
    CMDVelData& operator=(const CMDVelData&) = default;
    CMDVelData& operator=(CMDVelData&&) = default;

    /**
     * One-shot constructor to initialize all data members.
     */
    CMDVelData(float linearX, float linearY, float linearZ, float angularX, float angularY, float angularZ) :
        linearX(linearX),
        linearY(linearY),
        linearZ(linearZ),
        angularX(angularX),
        angularY(angularY),
        angularZ(angularZ)
    {
    }

    /**
     * Obtains a tuple containing all of the value's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const float&, const float&, const float&, const float&, const float&, const float&> ice_tuple() const
    {
        return std::tie(linearX, linearY, linearZ, angularX, angularY, angularZ);
    }

    /**
     * Obtains the Slice type ID of this value.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    float linearX;
    float linearY;
    float linearZ;
    float angularX;
    float angularY;
    float angularZ;
};

/// \cond INTERNAL
static CMDVelData _iceS_CMDVelData_init;
/// \endcond

}

namespace jderobot
{

class CMDVelPrx : public virtual ::Ice::Proxy<CMDVelPrx, ::Ice::ObjectPrx>
{
public:

    int setCMDVelData(const ::std::shared_ptr<CMDVelData>& data, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<int>(true, this, &CMDVelPrx::_iceI_setCMDVelData, data, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto setCMDVelDataAsync(const ::std::shared_ptr<CMDVelData>& data, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<int>>().get_future())
    {
        return _makePromiseOutgoing<int, P>(false, this, &CMDVelPrx::_iceI_setCMDVelData, data, context);
    }

    ::std::function<void()>
    setCMDVelDataAsync(const ::std::shared_ptr<CMDVelData>& data,
                       ::std::function<void(int)> response,
                       ::std::function<void(::std::exception_ptr)> ex = nullptr,
                       ::std::function<void(bool)> sent = nullptr,
                       const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<int>(response, ex, sent, this, &jderobot::CMDVelPrx::_iceI_setCMDVelData, data, context);
    }

    /// \cond INTERNAL
    void _iceI_setCMDVelData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, const ::std::shared_ptr<CMDVelData>&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    CMDVelPrx() = default;
    friend ::std::shared_ptr<CMDVelPrx> IceInternal::createProxy<CMDVelPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<typename S>
struct StreamReader<::jderobot::CMDVelData, S>
{
    static void read(S* istr, ::jderobot::CMDVelData& v)
    {
        istr->readAll(v.linearX, v.linearY, v.linearZ, v.angularX, v.angularY, v.angularZ);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace jderobot
{

using CMDVelDataPtr = ::std::shared_ptr<CMDVelData>;

using CMDVelPtr = ::std::shared_ptr<CMDVel>;
using CMDVelPrxPtr = ::std::shared_ptr<CMDVelPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace jderobot
{

class CMDVelData;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< CMDVelData>&);
::IceProxy::Ice::Object* upCast(CMDVelData*);
/// \endcond

class CMDVel;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< CMDVel>&);
::IceProxy::Ice::Object* upCast(CMDVel*);
/// \endcond

}

}

namespace jderobot
{

class CMDVelData;
/// \cond INTERNAL
::Ice::Object* upCast(CMDVelData*);
/// \endcond
typedef ::IceInternal::Handle< CMDVelData> CMDVelDataPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::jderobot::CMDVelData> CMDVelDataPrx;
typedef CMDVelDataPrx CMDVelDataPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(CMDVelDataPtr&, const ::Ice::ObjectPtr&);
/// \endcond

class CMDVel;
/// \cond INTERNAL
::Ice::Object* upCast(CMDVel*);
/// \endcond
typedef ::IceInternal::Handle< CMDVel> CMDVelPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::jderobot::CMDVel> CMDVelPrx;
typedef CMDVelPrx CMDVelPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(CMDVelPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace jderobot
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::jderobot::CMDVel::begin_setCMDVelData.
 * Create a wrapper instance by calling ::jderobot::newCallback_CMDVel_setCMDVelData.
 */
class Callback_CMDVel_setCMDVelData_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CMDVel_setCMDVelData_Base> Callback_CMDVel_setCMDVelDataPtr;

}

namespace IceProxy
{

namespace jderobot
{

class CMDVelData : public virtual ::Ice::Proxy<CMDVelData, ::IceProxy::Ice::Object>
{
public:

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

class CMDVel : public virtual ::Ice::Proxy<CMDVel, ::IceProxy::Ice::Object>
{
public:

    ::Ice::Int setCMDVelData(const ::jderobot::CMDVelDataPtr& data, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_setCMDVelData(_iceI_begin_setCMDVelData(data, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_setCMDVelData(const ::jderobot::CMDVelDataPtr& data, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_setCMDVelData(data, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setCMDVelData(const ::jderobot::CMDVelDataPtr& data, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setCMDVelData(data, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_setCMDVelData(const ::jderobot::CMDVelDataPtr& data, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setCMDVelData(data, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_setCMDVelData(const ::jderobot::CMDVelDataPtr& data, const ::jderobot::Callback_CMDVel_setCMDVelDataPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setCMDVelData(data, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_setCMDVelData(const ::jderobot::CMDVelDataPtr& data, const ::Ice::Context& context, const ::jderobot::Callback_CMDVel_setCMDVelDataPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setCMDVelData(data, context, cb, cookie);
    }

    ::Ice::Int end_setCMDVelData(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_setCMDVelData(const ::jderobot::CMDVelDataPtr&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace jderobot
{

class CMDVelData : public virtual ::Ice::Object
{
public:

    typedef CMDVelDataPrx ProxyType;
    typedef CMDVelDataPtr PointerType;

    virtual ~CMDVelData();

    CMDVelData()
    {
    }

    /**
     * One-shot constructor to initialize all data members.
     */
    CMDVelData(::Ice::Float linearX, ::Ice::Float linearY, ::Ice::Float linearZ, ::Ice::Float angularX, ::Ice::Float angularY, ::Ice::Float angularZ) :
        linearX(linearX),
        linearY(linearY),
        linearZ(linearZ),
        angularX(angularX),
        angularY(angularY),
        angularZ(angularZ)
    {
    }

    /**
     * Polymporphically clones this object.
     * @return A shallow copy of this object.
     */
    virtual ::Ice::ObjectPtr ice_clone() const;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    /**
     * Obtains a value factory that instantiates this class.
     * @return The value factory.
     */
    static ::Ice::ValueFactoryPtr ice_factory();

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond

public:

    ::Ice::Float linearX;
    ::Ice::Float linearY;
    ::Ice::Float linearZ;
    ::Ice::Float angularX;
    ::Ice::Float angularY;
    ::Ice::Float angularZ;
};
/// \cond INTERNAL
static ::Ice::ValueFactoryPtr _iceS_CMDVelData_init = ::jderobot::CMDVelData::ice_factory();
/// \endcond

/// \cond INTERNAL
inline bool operator==(const CMDVelData& lhs, const CMDVelData& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const CMDVelData& lhs, const CMDVelData& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

class CMDVel : public virtual ::Ice::Object
{
public:

    typedef CMDVelPrx ProxyType;
    typedef CMDVelPtr PointerType;

    virtual ~CMDVel();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual ::Ice::Int setCMDVelData(const CMDVelDataPtr& data, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_setCMDVelData(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const CMDVel& lhs, const CMDVel& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const CMDVel& lhs, const CMDVel& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<typename S>
struct StreamWriter< ::jderobot::CMDVelData, S>
{
    static void write(S* ostr, const ::jderobot::CMDVelData& v)
    {
        ostr->write(v.linearX);
        ostr->write(v.linearY);
        ostr->write(v.linearZ);
        ostr->write(v.angularX);
        ostr->write(v.angularY);
        ostr->write(v.angularZ);
    }
};

template<typename S>
struct StreamReader< ::jderobot::CMDVelData, S>
{
    static void read(S* istr, ::jderobot::CMDVelData& v)
    {
        istr->read(v.linearX);
        istr->read(v.linearY);
        istr->read(v.linearZ);
        istr->read(v.angularX);
        istr->read(v.angularY);
        istr->read(v.angularZ);
    }
};

}
/// \endcond

namespace jderobot
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::jderobot::CMDVel::begin_setCMDVelData.
 * Create a wrapper instance by calling ::jderobot::newCallback_CMDVel_setCMDVelData.
 */
template<class T>
class CallbackNC_CMDVel_setCMDVelData : public Callback_CMDVel_setCMDVelData_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_CMDVel_setCMDVelData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CMDVelPrx proxy = CMDVelPrx::uncheckedCast(result->getProxy());
        ::Ice::Int ret;
        try
        {
            ret = proxy->end_setCMDVelData(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::jderobot::CMDVel::begin_setCMDVelData.
 */
template<class T> Callback_CMDVel_setCMDVelDataPtr
newCallback_CMDVel_setCMDVelData(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CMDVel_setCMDVelData<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::jderobot::CMDVel::begin_setCMDVelData.
 */
template<class T> Callback_CMDVel_setCMDVelDataPtr
newCallback_CMDVel_setCMDVelData(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CMDVel_setCMDVelData<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::jderobot::CMDVel::begin_setCMDVelData.
 * Create a wrapper instance by calling ::jderobot::newCallback_CMDVel_setCMDVelData.
 */
template<class T, typename CT>
class Callback_CMDVel_setCMDVelData : public Callback_CMDVel_setCMDVelData_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_CMDVel_setCMDVelData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CMDVelPrx proxy = CMDVelPrx::uncheckedCast(result->getProxy());
        ::Ice::Int ret;
        try
        {
            ret = proxy->end_setCMDVelData(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::jderobot::CMDVel::begin_setCMDVelData.
 */
template<class T, typename CT> Callback_CMDVel_setCMDVelDataPtr
newCallback_CMDVel_setCMDVelData(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CMDVel_setCMDVelData<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::jderobot::CMDVel::begin_setCMDVelData.
 */
template<class T, typename CT> Callback_CMDVel_setCMDVelDataPtr
newCallback_CMDVel_setCMDVelData(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CMDVel_setCMDVelData<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
