//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `recorder.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __jderobot_recorder_h__
#define __jderobot_recorder_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace jderobot
{

class recorder;
class recorderPrx;

}

namespace jderobot
{

class recorder : public virtual ::Ice::Object
{
public:

    using ProxyType = recorderPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual bool saveLog(::std::string name, int seconds, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_saveLog(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual bool saveVideo(::std::string path, ::std::string name, int seconds, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_saveVideo(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace jderobot
{

class recorderPrx : public virtual ::Ice::Proxy<recorderPrx, ::Ice::ObjectPrx>
{
public:

    bool saveLog(const ::std::string& name, int seconds, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<bool>(true, this, &recorderPrx::_iceI_saveLog, name, seconds, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto saveLogAsync(const ::std::string& name, int seconds, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<bool>>().get_future())
    {
        return _makePromiseOutgoing<bool, P>(false, this, &recorderPrx::_iceI_saveLog, name, seconds, context);
    }

    ::std::function<void()>
    saveLogAsync(const ::std::string& name, int seconds,
                 ::std::function<void(bool)> response,
                 ::std::function<void(::std::exception_ptr)> ex = nullptr,
                 ::std::function<void(bool)> sent = nullptr,
                 const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<bool>(response, ex, sent, this, &jderobot::recorderPrx::_iceI_saveLog, name, seconds, context);
    }

    /// \cond INTERNAL
    void _iceI_saveLog(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>&, const ::std::string&, int, const ::Ice::Context&);
    /// \endcond

    bool saveVideo(const ::std::string& path, const ::std::string& name, int seconds, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<bool>(true, this, &recorderPrx::_iceI_saveVideo, path, name, seconds, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto saveVideoAsync(const ::std::string& path, const ::std::string& name, int seconds, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<bool>>().get_future())
    {
        return _makePromiseOutgoing<bool, P>(false, this, &recorderPrx::_iceI_saveVideo, path, name, seconds, context);
    }

    ::std::function<void()>
    saveVideoAsync(const ::std::string& path, const ::std::string& name, int seconds,
                   ::std::function<void(bool)> response,
                   ::std::function<void(::std::exception_ptr)> ex = nullptr,
                   ::std::function<void(bool)> sent = nullptr,
                   const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<bool>(response, ex, sent, this, &jderobot::recorderPrx::_iceI_saveVideo, path, name, seconds, context);
    }

    /// \cond INTERNAL
    void _iceI_saveVideo(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>&, const ::std::string&, const ::std::string&, int, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    recorderPrx() = default;
    friend ::std::shared_ptr<recorderPrx> IceInternal::createProxy<recorderPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

/// \cond INTERNAL
namespace jderobot
{

using recorderPtr = ::std::shared_ptr<recorder>;
using recorderPrxPtr = ::std::shared_ptr<recorderPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace jderobot
{

class recorder;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< recorder>&);
::IceProxy::Ice::Object* upCast(recorder*);
/// \endcond

}

}

namespace jderobot
{

class recorder;
/// \cond INTERNAL
::Ice::Object* upCast(recorder*);
/// \endcond
typedef ::IceInternal::Handle< recorder> recorderPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::jderobot::recorder> recorderPrx;
typedef recorderPrx recorderPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(recorderPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace jderobot
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::jderobot::recorder::begin_saveLog.
 * Create a wrapper instance by calling ::jderobot::newCallback_recorder_saveLog.
 */
class Callback_recorder_saveLog_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_recorder_saveLog_Base> Callback_recorder_saveLogPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::jderobot::recorder::begin_saveVideo.
 * Create a wrapper instance by calling ::jderobot::newCallback_recorder_saveVideo.
 */
class Callback_recorder_saveVideo_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_recorder_saveVideo_Base> Callback_recorder_saveVideoPtr;

}

namespace IceProxy
{

namespace jderobot
{

class recorder : public virtual ::Ice::Proxy<recorder, ::IceProxy::Ice::Object>
{
public:

    bool saveLog(const ::std::string& name, ::Ice::Int seconds, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_saveLog(_iceI_begin_saveLog(name, seconds, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_saveLog(const ::std::string& name, ::Ice::Int seconds, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_saveLog(name, seconds, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_saveLog(const ::std::string& name, ::Ice::Int seconds, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_saveLog(name, seconds, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_saveLog(const ::std::string& name, ::Ice::Int seconds, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_saveLog(name, seconds, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_saveLog(const ::std::string& name, ::Ice::Int seconds, const ::jderobot::Callback_recorder_saveLogPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_saveLog(name, seconds, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_saveLog(const ::std::string& name, ::Ice::Int seconds, const ::Ice::Context& context, const ::jderobot::Callback_recorder_saveLogPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_saveLog(name, seconds, context, cb, cookie);
    }

    bool end_saveLog(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_saveLog(const ::std::string&, ::Ice::Int, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    bool saveVideo(const ::std::string& path, const ::std::string& name, ::Ice::Int seconds, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_saveVideo(_iceI_begin_saveVideo(path, name, seconds, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_saveVideo(const ::std::string& path, const ::std::string& name, ::Ice::Int seconds, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_saveVideo(path, name, seconds, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_saveVideo(const ::std::string& path, const ::std::string& name, ::Ice::Int seconds, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_saveVideo(path, name, seconds, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_saveVideo(const ::std::string& path, const ::std::string& name, ::Ice::Int seconds, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_saveVideo(path, name, seconds, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_saveVideo(const ::std::string& path, const ::std::string& name, ::Ice::Int seconds, const ::jderobot::Callback_recorder_saveVideoPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_saveVideo(path, name, seconds, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_saveVideo(const ::std::string& path, const ::std::string& name, ::Ice::Int seconds, const ::Ice::Context& context, const ::jderobot::Callback_recorder_saveVideoPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_saveVideo(path, name, seconds, context, cb, cookie);
    }

    bool end_saveVideo(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_saveVideo(const ::std::string&, const ::std::string&, ::Ice::Int, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace jderobot
{

class recorder : public virtual ::Ice::Object
{
public:

    typedef recorderPrx ProxyType;
    typedef recorderPtr PointerType;

    virtual ~recorder();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual bool saveLog(const ::std::string& name, ::Ice::Int seconds, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_saveLog(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual bool saveVideo(const ::std::string& path, const ::std::string& name, ::Ice::Int seconds, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_saveVideo(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const recorder& lhs, const recorder& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const recorder& lhs, const recorder& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

namespace jderobot
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::jderobot::recorder::begin_saveLog.
 * Create a wrapper instance by calling ::jderobot::newCallback_recorder_saveLog.
 */
template<class T>
class CallbackNC_recorder_saveLog : public Callback_recorder_saveLog_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_recorder_saveLog(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        recorderPrx proxy = recorderPrx::uncheckedCast(result->getProxy());
        bool ret;
        try
        {
            ret = proxy->end_saveLog(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::jderobot::recorder::begin_saveLog.
 */
template<class T> Callback_recorder_saveLogPtr
newCallback_recorder_saveLog(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_recorder_saveLog<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::jderobot::recorder::begin_saveLog.
 */
template<class T> Callback_recorder_saveLogPtr
newCallback_recorder_saveLog(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_recorder_saveLog<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::jderobot::recorder::begin_saveLog.
 * Create a wrapper instance by calling ::jderobot::newCallback_recorder_saveLog.
 */
template<class T, typename CT>
class Callback_recorder_saveLog : public Callback_recorder_saveLog_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_recorder_saveLog(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        recorderPrx proxy = recorderPrx::uncheckedCast(result->getProxy());
        bool ret;
        try
        {
            ret = proxy->end_saveLog(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::jderobot::recorder::begin_saveLog.
 */
template<class T, typename CT> Callback_recorder_saveLogPtr
newCallback_recorder_saveLog(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_recorder_saveLog<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::jderobot::recorder::begin_saveLog.
 */
template<class T, typename CT> Callback_recorder_saveLogPtr
newCallback_recorder_saveLog(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_recorder_saveLog<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::jderobot::recorder::begin_saveVideo.
 * Create a wrapper instance by calling ::jderobot::newCallback_recorder_saveVideo.
 */
template<class T>
class CallbackNC_recorder_saveVideo : public Callback_recorder_saveVideo_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_recorder_saveVideo(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        recorderPrx proxy = recorderPrx::uncheckedCast(result->getProxy());
        bool ret;
        try
        {
            ret = proxy->end_saveVideo(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::jderobot::recorder::begin_saveVideo.
 */
template<class T> Callback_recorder_saveVideoPtr
newCallback_recorder_saveVideo(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_recorder_saveVideo<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::jderobot::recorder::begin_saveVideo.
 */
template<class T> Callback_recorder_saveVideoPtr
newCallback_recorder_saveVideo(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_recorder_saveVideo<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::jderobot::recorder::begin_saveVideo.
 * Create a wrapper instance by calling ::jderobot::newCallback_recorder_saveVideo.
 */
template<class T, typename CT>
class Callback_recorder_saveVideo : public Callback_recorder_saveVideo_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_recorder_saveVideo(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        recorderPrx proxy = recorderPrx::uncheckedCast(result->getProxy());
        bool ret;
        try
        {
            ret = proxy->end_saveVideo(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::jderobot::recorder::begin_saveVideo.
 */
template<class T, typename CT> Callback_recorder_saveVideoPtr
newCallback_recorder_saveVideo(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_recorder_saveVideo<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::jderobot::recorder::begin_saveVideo.
 */
template<class T, typename CT> Callback_recorder_saveVideoPtr
newCallback_recorder_saveVideo(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_recorder_saveVideo<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
