# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.3
#
# <auto-generated>
#
# Generated from file `namingService.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module jderobot
_M_jderobot = Ice.openModule('jderobot')
__name__ = 'jderobot'

if 'Time' not in _M_jderobot.__dict__:
    _M_jderobot.Time = Ice.createTempClass()
    class Time(object):
        def __init__(self, seconds=0, useconds=0):
            self.seconds = seconds
            self.useconds = useconds

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.seconds)
            _h = 5 * _h + Ice.getHash(self.useconds)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_jderobot.Time):
                return NotImplemented
            else:
                if self.seconds is None or other.seconds is None:
                    if self.seconds != other.seconds:
                        return (-1 if self.seconds is None else 1)
                else:
                    if self.seconds < other.seconds:
                        return -1
                    elif self.seconds > other.seconds:
                        return 1
                if self.useconds is None or other.useconds is None:
                    if self.useconds != other.useconds:
                        return (-1 if self.useconds is None else 1)
                else:
                    if self.useconds < other.useconds:
                        return -1
                    elif self.useconds > other.useconds:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_Time)

        __repr__ = __str__

    _M_jderobot._t_Time = IcePy.defineStruct('::jderobot::Time', Time, (), (
        ('seconds', (), IcePy._t_long),
        ('useconds', (), IcePy._t_long)
    ))

    _M_jderobot.Time = Time
    del Time

# End of module jderobot

# Start of module jderobot
__name__ = 'jderobot'

if 'JderobotException' not in _M_jderobot.__dict__:
    _M_jderobot.JderobotException = Ice.createTempClass()
    class JderobotException(Ice.UserException):
        def __init__(self, what=''):
            self.what = what

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::jderobot::JderobotException'

    _M_jderobot._t_JderobotException = IcePy.defineException('::jderobot::JderobotException', JderobotException, (), False, None, (('what', (), IcePy._t_string, False, 0),))
    JderobotException._ice_type = _M_jderobot._t_JderobotException

    _M_jderobot.JderobotException = JderobotException
    del JderobotException

if 'ConfigurationNotExistException' not in _M_jderobot.__dict__:
    _M_jderobot.ConfigurationNotExistException = Ice.createTempClass()
    class ConfigurationNotExistException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::jderobot::ConfigurationNotExistException'

    _M_jderobot._t_ConfigurationNotExistException = IcePy.defineException('::jderobot::ConfigurationNotExistException', ConfigurationNotExistException, (), False, _M_jderobot._t_JderobotException, ())
    ConfigurationNotExistException._ice_type = _M_jderobot._t_ConfigurationNotExistException

    _M_jderobot.ConfigurationNotExistException = ConfigurationNotExistException
    del ConfigurationNotExistException

if 'DataNotExistException' not in _M_jderobot.__dict__:
    _M_jderobot.DataNotExistException = Ice.createTempClass()
    class DataNotExistException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::jderobot::DataNotExistException'

    _M_jderobot._t_DataNotExistException = IcePy.defineException('::jderobot::DataNotExistException', DataNotExistException, (), False, _M_jderobot._t_JderobotException, ())
    DataNotExistException._ice_type = _M_jderobot._t_DataNotExistException

    _M_jderobot.DataNotExistException = DataNotExistException
    del DataNotExistException

if 'HardwareFailedException' not in _M_jderobot.__dict__:
    _M_jderobot.HardwareFailedException = Ice.createTempClass()
    class HardwareFailedException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::jderobot::HardwareFailedException'

    _M_jderobot._t_HardwareFailedException = IcePy.defineException('::jderobot::HardwareFailedException', HardwareFailedException, (), False, _M_jderobot._t_JderobotException, ())
    HardwareFailedException._ice_type = _M_jderobot._t_HardwareFailedException

    _M_jderobot.HardwareFailedException = HardwareFailedException
    del HardwareFailedException

if 'NoTopicException' not in _M_jderobot.__dict__:
    _M_jderobot.NoTopicException = Ice.createTempClass()
    class NoTopicException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::jderobot::NoTopicException'

    _M_jderobot._t_NoTopicException = IcePy.defineException('::jderobot::NoTopicException', NoTopicException, (), False, _M_jderobot._t_JderobotException, ())
    NoTopicException._ice_type = _M_jderobot._t_NoTopicException

    _M_jderobot.NoTopicException = NoTopicException
    del NoTopicException

if 'SubscriptionFailedException' not in _M_jderobot.__dict__:
    _M_jderobot.SubscriptionFailedException = Ice.createTempClass()
    class SubscriptionFailedException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::jderobot::SubscriptionFailedException'

    _M_jderobot._t_SubscriptionFailedException = IcePy.defineException('::jderobot::SubscriptionFailedException', SubscriptionFailedException, (), False, _M_jderobot._t_JderobotException, ())
    SubscriptionFailedException._ice_type = _M_jderobot._t_SubscriptionFailedException

    _M_jderobot.SubscriptionFailedException = SubscriptionFailedException
    del SubscriptionFailedException

if 'SubscriptionPushFailedException' not in _M_jderobot.__dict__:
    _M_jderobot.SubscriptionPushFailedException = Ice.createTempClass()
    class SubscriptionPushFailedException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::jderobot::SubscriptionPushFailedException'

    _M_jderobot._t_SubscriptionPushFailedException = IcePy.defineException('::jderobot::SubscriptionPushFailedException', SubscriptionPushFailedException, (), False, _M_jderobot._t_JderobotException, ())
    SubscriptionPushFailedException._ice_type = _M_jderobot._t_SubscriptionPushFailedException

    _M_jderobot.SubscriptionPushFailedException = SubscriptionPushFailedException
    del SubscriptionPushFailedException

# End of module jderobot

# Start of module jderobot
__name__ = 'jderobot'

if '_t_ByteSeq' not in _M_jderobot.__dict__:
    _M_jderobot._t_ByteSeq = IcePy.defineSequence('::jderobot::ByteSeq', (), IcePy._t_byte)

if '_t_IntSeq' not in _M_jderobot.__dict__:
    _M_jderobot._t_IntSeq = IcePy.defineSequence('::jderobot::IntSeq', (), IcePy._t_int)

if '_t_seqFloat' not in _M_jderobot.__dict__:
    _M_jderobot._t_seqFloat = IcePy.defineSequence('::jderobot::seqFloat', (), IcePy._t_float)

# End of module jderobot

# Start of module jderobot
__name__ = 'jderobot'

# End of module jderobot

# Start of module jderobot
__name__ = 'jderobot'

if 'NameAlreadyExistException' not in _M_jderobot.__dict__:
    _M_jderobot.NameAlreadyExistException = Ice.createTempClass()
    class NameAlreadyExistException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::jderobot::NameAlreadyExistException'

    _M_jderobot._t_NameAlreadyExistException = IcePy.defineException('::jderobot::NameAlreadyExistException', NameAlreadyExistException, (), False, _M_jderobot._t_JderobotException, ())
    NameAlreadyExistException._ice_type = _M_jderobot._t_NameAlreadyExistException

    _M_jderobot.NameAlreadyExistException = NameAlreadyExistException
    del NameAlreadyExistException

if 'NameNotExistException' not in _M_jderobot.__dict__:
    _M_jderobot.NameNotExistException = Ice.createTempClass()
    class NameNotExistException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::jderobot::NameNotExistException'

    _M_jderobot._t_NameNotExistException = IcePy.defineException('::jderobot::NameNotExistException', NameNotExistException, (), False, _M_jderobot._t_JderobotException, ())
    NameNotExistException._ice_type = _M_jderobot._t_NameNotExistException

    _M_jderobot.NameNotExistException = NameNotExistException
    del NameNotExistException

if 'InterfaceNotExistException' not in _M_jderobot.__dict__:
    _M_jderobot.InterfaceNotExistException = Ice.createTempClass()
    class InterfaceNotExistException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::jderobot::InterfaceNotExistException'

    _M_jderobot._t_InterfaceNotExistException = IcePy.defineException('::jderobot::InterfaceNotExistException', InterfaceNotExistException, (), False, _M_jderobot._t_JderobotException, ())
    InterfaceNotExistException._ice_type = _M_jderobot._t_InterfaceNotExistException

    _M_jderobot.InterfaceNotExistException = InterfaceNotExistException
    del InterfaceNotExistException

if 'NamingNode' not in _M_jderobot.__dict__:
    _M_jderobot.NamingNode = Ice.createTempClass()
    class NamingNode(Ice.Value):
        def __init__(self, name='', interfaceName='', protocol='', ip='', port=0):
            self.name = name
            self.interfaceName = interfaceName
            self.protocol = protocol
            self.ip = ip
            self.port = port

        def ice_id(self):
            return '::jderobot::NamingNode'

        @staticmethod
        def ice_staticId():
            return '::jderobot::NamingNode'

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_NamingNode)

        __repr__ = __str__

    _M_jderobot._t_NamingNode = IcePy.defineValue('::jderobot::NamingNode', NamingNode, -1, (), False, False, None, (
        ('name', (), IcePy._t_string, False, 0),
        ('interfaceName', (), IcePy._t_string, False, 0),
        ('protocol', (), IcePy._t_string, False, 0),
        ('ip', (), IcePy._t_string, False, 0),
        ('port', (), IcePy._t_int, False, 0)
    ))
    NamingNode._ice_type = _M_jderobot._t_NamingNode

    _M_jderobot.NamingNode = NamingNode
    del NamingNode

if '_t_nodeList' not in _M_jderobot.__dict__:
    _M_jderobot._t_nodeList = IcePy.defineSequence('::jderobot::nodeList', (), _M_jderobot._t_NamingNode)

if 'NodeContainer' not in _M_jderobot.__dict__:
    _M_jderobot.NodeContainer = Ice.createTempClass()
    class NodeContainer(Ice.Value):
        def __init__(self, nodes=None):
            self.nodes = nodes

        def ice_id(self):
            return '::jderobot::NodeContainer'

        @staticmethod
        def ice_staticId():
            return '::jderobot::NodeContainer'

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_NodeContainer)

        __repr__ = __str__

    _M_jderobot._t_NodeContainer = IcePy.declareValue('::jderobot::NodeContainer')

    _M_jderobot._t_NodeContainer = IcePy.defineValue('::jderobot::NodeContainer', NodeContainer, -1, (), False, False, None, (('nodes', (), _M_jderobot._t_nodeList, False, 0),))
    NodeContainer._ice_type = _M_jderobot._t_NodeContainer

    _M_jderobot.NodeContainer = NodeContainer
    del NodeContainer

_M_jderobot._t_NamingService = IcePy.defineValue('::jderobot::NamingService', Ice.Value, -1, (), False, True, None, ())

if 'NamingServicePrx' not in _M_jderobot.__dict__:
    _M_jderobot.NamingServicePrx = Ice.createTempClass()
    class NamingServicePrx(Ice.ObjectPrx):

        def bind(self, node, context=None):
            return _M_jderobot.NamingService._op_bind.invoke(self, ((node, ), context))

        def bindAsync(self, node, context=None):
            return _M_jderobot.NamingService._op_bind.invokeAsync(self, ((node, ), context))

        def begin_bind(self, node, _response=None, _ex=None, _sent=None, context=None):
            return _M_jderobot.NamingService._op_bind.begin(self, ((node, ), _response, _ex, _sent, context))

        def end_bind(self, _r):
            return _M_jderobot.NamingService._op_bind.end(self, _r)

        def unbind(self, node, context=None):
            return _M_jderobot.NamingService._op_unbind.invoke(self, ((node, ), context))

        def unbindAsync(self, node, context=None):
            return _M_jderobot.NamingService._op_unbind.invokeAsync(self, ((node, ), context))

        def begin_unbind(self, node, _response=None, _ex=None, _sent=None, context=None):
            return _M_jderobot.NamingService._op_unbind.begin(self, ((node, ), _response, _ex, _sent, context))

        def end_unbind(self, _r):
            return _M_jderobot.NamingService._op_unbind.end(self, _r)

        def resolveByName(self, name, context=None):
            return _M_jderobot.NamingService._op_resolveByName.invoke(self, ((name, ), context))

        def resolveByNameAsync(self, name, context=None):
            return _M_jderobot.NamingService._op_resolveByName.invokeAsync(self, ((name, ), context))

        def begin_resolveByName(self, name, _response=None, _ex=None, _sent=None, context=None):
            return _M_jderobot.NamingService._op_resolveByName.begin(self, ((name, ), _response, _ex, _sent, context))

        def end_resolveByName(self, _r):
            return _M_jderobot.NamingService._op_resolveByName.end(self, _r)

        def resolveByInterface(self, interfaceName, context=None):
            return _M_jderobot.NamingService._op_resolveByInterface.invoke(self, ((interfaceName, ), context))

        def resolveByInterfaceAsync(self, interfaceName, context=None):
            return _M_jderobot.NamingService._op_resolveByInterface.invokeAsync(self, ((interfaceName, ), context))

        def begin_resolveByInterface(self, interfaceName, _response=None, _ex=None, _sent=None, context=None):
            return _M_jderobot.NamingService._op_resolveByInterface.begin(self, ((interfaceName, ), _response, _ex, _sent, context))

        def end_resolveByInterface(self, _r):
            return _M_jderobot.NamingService._op_resolveByInterface.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_jderobot.NamingServicePrx.ice_checkedCast(proxy, '::jderobot::NamingService', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_jderobot.NamingServicePrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::jderobot::NamingService'
    _M_jderobot._t_NamingServicePrx = IcePy.defineProxy('::jderobot::NamingService', NamingServicePrx)

    _M_jderobot.NamingServicePrx = NamingServicePrx
    del NamingServicePrx

    _M_jderobot.NamingService = Ice.createTempClass()
    class NamingService(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::jderobot::NamingService')

        def ice_id(self, current=None):
            return '::jderobot::NamingService'

        @staticmethod
        def ice_staticId():
            return '::jderobot::NamingService'

        def bind(self, node, current=None):
            raise NotImplementedError("servant method 'bind' not implemented")

        def unbind(self, node, current=None):
            raise NotImplementedError("servant method 'unbind' not implemented")

        def resolveByName(self, name, current=None):
            raise NotImplementedError("servant method 'resolveByName' not implemented")

        def resolveByInterface(self, interfaceName, current=None):
            raise NotImplementedError("servant method 'resolveByInterface' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_NamingServiceDisp)

        __repr__ = __str__

    _M_jderobot._t_NamingServiceDisp = IcePy.defineClass('::jderobot::NamingService', NamingService, (), None, ())
    NamingService._ice_type = _M_jderobot._t_NamingServiceDisp

    NamingService._op_bind = IcePy.Operation('bind', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_jderobot._t_NamingNode, False, 0),), (), None, (_M_jderobot._t_NameAlreadyExistException,))
    NamingService._op_unbind = IcePy.Operation('unbind', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_jderobot._t_NamingNode, False, 0),), (), None, (_M_jderobot._t_NameAlreadyExistException, _M_jderobot._t_NameNotExistException))
    NamingService._op_resolveByName = IcePy.Operation('resolveByName', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), _M_jderobot._t_NodeContainer, False, 0), (_M_jderobot._t_NameNotExistException,))
    NamingService._op_resolveByInterface = IcePy.Operation('resolveByInterface', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), _M_jderobot._t_NodeContainer, False, 0), (_M_jderobot._t_InterfaceNotExistException,))

    _M_jderobot.NamingService = NamingService
    del NamingService

# End of module jderobot
